id: P008229
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W30362
  title: ཕྱི་རྒྱལ་གྱི་དམངས་ཁྲོད་གཏམ་རྒྱུད་བདམས་སྒྲིག
  author: ''
  volumes:
    c8a19492fe204848a134ffc00b6a55c8:
      image_group_id: I1KG18476
      title: ''
      volume_number: 1
      total_pages: 288
      base_file: v001.txt
